
# ./parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'E9B739A7E15DC6A8318C9E1BF6B5E02B'
    
_lr_action_items = {'TIME_VALS':([5,],[12,]),'INT_VAL':([1,4,14,29,],[5,9,20,33,]),'MORELESS':([24,25,26,],[29,29,29,]),'LBRACKET':([12,],[19,]),'$end':([3,6,13,],[0,-1,-2,]),'INDEF':([4,],[10,]),'REPEAT':([0,6,19,],[1,1,1,]),'PREFIX':([7,8,10,17,18,22,24,25,26,30,31,32,33,34,],[-17,15,-16,-15,-14,15,-13,-13,-13,-10,-8,-9,-11,-12,]),'RBRACKET':([6,13,23,],[-1,-2,28,]),'SEMI':([2,7,8,10,15,16,17,18,22,24,25,26,27,28,30,31,32,33,34,],[6,-17,-7,-16,-6,-3,-15,-14,-7,-13,-13,-13,-4,-5,-10,-8,-9,-11,-12,]),'TIME_VAL':([4,],[7,]),'PERCENT':([20,],[25,]),'KMH':([20,21,],[24,26,]),'AT':([7,8,10,17,18,],[-17,14,-16,-15,-14,]),'KM':([9,11,],[17,18,]),'RUN':([0,6,19,],[4,4,4,]),'FLOAT_VAL':([4,14,29,],[11,21,34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'duration':([4,],[8,]),'margin':([24,25,26,],[30,31,32,]),'step':([0,6,19,],[2,2,2,]),'trainingSession':([0,6,19,],[3,13,23,]),'target':([14,],[22,]),'prefix':([8,22,],[16,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> trainingSession","S'",1,None,None,None),
  ('trainingSession -> step SEMI','trainingSession',2,'p_trainingSession','generateCode.py',68),
  ('trainingSession -> step SEMI trainingSession','trainingSession',3,'p_trainingSession','generateCode.py',69),
  ('step -> RUN duration prefix','step',3,'p_step','generateCode.py',80),
  ('step -> RUN duration AT target prefix','step',5,'p_step','generateCode.py',81),
  ('step -> REPEAT INT_VAL TIME_VALS LBRACKET trainingSession RBRACKET','step',6,'p_step','generateCode.py',82),
  ('prefix -> PREFIX','prefix',1,'p_prefix','generateCode.py',96),
  ('prefix -> <empty>','prefix',0,'p_prefix','generateCode.py',97),
  ('target -> INT_VAL PERCENT margin','target',3,'p_target_percent','generateCode.py',105),
  ('target -> FLOAT_VAL KMH margin','target',3,'p_target_percent','generateCode.py',106),
  ('target -> INT_VAL KMH margin','target',3,'p_target_percent','generateCode.py',107),
  ('margin -> MORELESS INT_VAL','margin',2,'p_margin','generateCode.py',116),
  ('margin -> MORELESS FLOAT_VAL','margin',2,'p_margin','generateCode.py',117),
  ('margin -> <empty>','margin',0,'p_margin','generateCode.py',118),
  ('duration -> FLOAT_VAL KM','duration',2,'p_duration','generateCode.py',125),
  ('duration -> INT_VAL KM','duration',2,'p_duration','generateCode.py',126),
  ('duration -> INDEF','duration',1,'p_duration','generateCode.py',127),
  ('duration -> TIME_VAL','duration',1,'p_duration','generateCode.py',128),
]
